version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        environment:  
            - PORT=3000
        depends_on:
            - mongo-db
    mongo-db:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=cahillwi
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
        volumes: 
            - mongo-db:/data/db
    redis:
        image: redis

volumes: 
    mongo-db: