version: "3"
services: 
    nginx:
        ports:
            - "3000:80"
    node-app:
        build: 
            context: .
            args:
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=cahillwi
            - MONGO_PASSWORD=mypassword
            - MONGO_IP=mongo-db
            - SESSION_SECRET=secret
        command: npm run dev-server
    mongo-db:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=cahillwi
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
            